hydra:
  run:
    dir: ./output/${parameters.model}_${parameters.dataset}

parameters:
  epochs: 200
  batch_size: 128
  verbose_step: 100
  verbose: True
  lr_init: 1.e-3
  log_dir: "./tboard"
  ckpts_dir: "./ckpts"
  model: "mnasnet-a1"
  dataset: "cifar10"
  dropout: 0.2
  num_classes: 10
  resume: None
  optimizer_reset: False
  inference: False  
